services:
  db:
    image: postgres:16-alpine
    container_name: room2room-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-room2room}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:


