"""housing exchange

Revision ID: 1ae9bbbeb8b3
Revises: 7eabcbd62ac2
Create Date: 2025-10-14 13:47:45.843713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae9bbbeb8b3'
down_revision = '7eabcbd62ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('housing_type', sa.String(length=64), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('housing_exchange', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_housing_exchange_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_housing_exchange_housing_type'), ['housing_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_housing_exchange_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housing_exchange', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_housing_exchange_owner_id'))
        batch_op.drop_index(batch_op.f('ix_housing_exchange_housing_type'))
        batch_op.drop_index(batch_op.f('ix_housing_exchange_city'))

    op.drop_table('housing_exchange')
    # ### end Alembic commands ###
