"""remote tourism

Revision ID: 781b84884cb2
Revises: 4abb7e24ab85
Create Date: 2025-10-16 17:49:25.361412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781b84884cb2'
down_revision = '4abb7e24ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_tourism',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_hour', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('available_dates', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('booking_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_tourism', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_tourism_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_tourism_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_tourism_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remote_tourism', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_tourism_is_active'))
        batch_op.drop_index(batch_op.f('ix_remote_tourism_guide_id'))
        batch_op.drop_index(batch_op.f('ix_remote_tourism_city'))

    op.drop_table('remote_tourism')
    # ### end Alembic commands ###
