"""tourism dates + reviews

Revision ID: a64fa9a373a1
Revises: 781b84884cb2
Create Date: 2025-10-16 18:13:38.275347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a64fa9a373a1'
down_revision = '781b84884cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('tourism_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['housing_exchange.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tourism_id'], ['remote_tourism.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_reviewed_id'), ['reviewed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('remote_tourism', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('available_to', sa.Date(), nullable=True))
        batch_op.drop_column('available_dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remote_tourism', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_dates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewed_id'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
