"""add hours to bookings

Revision ID: c15e753b2e64
Revises: 885f92fa00a0
Create Date: 2025-10-18 01:47:38.245258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15e753b2e64'
down_revision = '885f92fa00a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавим колонку как nullable
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.Integer(), nullable=True))
    
    # Заполним существующие записи значением по умолчанию
    op.execute("UPDATE bookings SET hours = 1 WHERE hours IS NULL")
    
    # Теперь сделаем колонку NOT NULL
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('hours', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('hours')

    # ### end Alembic commands ###
